CustomizableWeaponry:addFireSound("CW_KK_INS2_SR25_FIRE", "weapons/sr25/sr25_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_SR25_FIRE_SUPPRESSED", "weapons/sr25/sr25_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_BOLTBACK", "weapons/sr25/handling/sr25_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_BOLTRELEASE", "weapons/sr25/handling/sr25_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_EMPTY", "weapons/sr25/handling/sr25_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_FIRESELECT", "weapons/sr25/handling/sr25_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_MAGIN", "weapons/sr25/handling/sr25_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_MAGOUT", "weapons/sr25/handling/sr25_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_MAGOUTRATTLE", "weapons/sr25/handling/sr25_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_MAGRELEASE", "weapons/sr25/handling/sr25_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_SR25_RATTLE", "weapons/sr25/handling/sr25_rattle.wav")
