CustomizableWeaponry:addFireSound("CW_KK_INS2_FREEDOM_FIRE", "weapons/freedom/mk18_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_FREEDOM_FIRE_SUPPRESSED", "weapons/freedom/mk18_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_BOLTBACK", "weapons/freedom/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_BOLTRELEASE", "weapons/freedom/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_EMPTY", "weapons/freedom/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_FIRESELECT", "weapons/freedom/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_HIT", "weapons/freedom/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_MAGIN", "weapons/freedom/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_MAGOUT", "weapons/freedom/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FREEDOM_MAGRELEASE", "weapons/freedom/handling/mk18_magrelease.wav")
