
TICKRATE = engine.TickInterval( )

--Distance
HAB_METERS_TO_SOURCE_ = 64 / 1.25
HAB_METERS_TO_SOURCE = HAB_METERS_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_MILIMETERS_TO_SOURCE_ = HAB_METERS_TO_SOURCE_ / 1000
HAB_MILIMETERS_TO_SOURCE = HAB_MILIMETERS_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_CENTIETERS_TO_SOURCE_ = HAB_METERS_TO_SOURCE_ / 100
HAB_CENTIETERS_TO_SOURCE = HAB_CENTIETERS_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_KILOMETERS_TO_SOURCE_ = HAB_METERS_TO_SOURCE_ * 1000
HAB_KILOMETERS_TO_SOURCE = HAB_KILOMETERS_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )


HAB_INCHES_TO_SOURCE_ = 1 / 0.75
HAB_INCHES_TO_SOURCE = HAB_INCHES_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_FEET_TO_SOURCE_ = HAB_INCHES_TO_SOURCE_ / 12
HAB_FEET_TO_SOURCE = HAB_FEET_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_YARDS_TO_SOURCE_ = HAB_FEET_TO_SOURCE_ / 3
HAB_YARDS_TO_SOURCE = HAB_YARDS_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

HAB_MILES_TO_SOURCE_ = HAB_YARDS_TO_SOURCE_ / 1760
HAB_MILES_TO_SOURCE = HAB_MILES_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

--Speed
HAB_MPH_TO_SOURCE_ = 15 / 352
HAB_MPH_TO_SOURCE = HAB_MPH_TO_SOURCE_ / cvars.Number( "hab_PFScale", 1 )

--Force
HAB_GRAVITY_ = 9.80665
HAB_GRAVITY = HAB_GRAVITY_ / cvars.Number( "hab_PFScale", 1 )
HAB_GRAVITY_SOURCE = HAB_GRAVITY * HAB_METERS_TO_SOURCE_

--Flags CVAR
HAB_FCVAR_SERVER_ONLY = { FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_SERVER_CAN_EXECUTE }
HAB_FCVAR_SERVER = { FCVAR_ARCHIVE, FCVAR_REPLICATED }

HAB_FCVAR_CLIENT_ONLY = { FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_CLIENTCMD_CAN_EXECUTE, FCVAR_USERINFO }
HAB_FCVAR_CLIENT = { FCVAR_ARCHIVE, FCVAR_REPLICATED, FCVAR_USERINFO }

HAB_FCVAR_CLIENT_SERVER_ONCE = FCVAR_USERINFO

--Colors (adapted from "https://raw.githubusercontent.com/Kefta/gs_lib/master/lua/code_gs/lib/color.lua")

HAB_COLOR_BLACK = Color( 0, 0, 0, 255 )
HAB_COLOR_WHITE = Color( 255, 255, 255, 255 )

HAB_COLOR_RED = Color( 255, 0, 0, 255 )
HAB_COLOR_ROSE = Color( 255, 0, 127, 255 )
HAB_COLOR_MAGENTA = Color( 255, 0, 255, 255 )
HAB_COLOR_VIOLET = Color( 127, 0, 255, 255 )
HAB_COLOR_BLUE = Color( 0, 0, 255, 255 )
HAB_COLOR_AZURE = Color( 0, 127, 255, 255 )
HAB_COLOR_CYAN = Color( 0, 255, 255, 255 )
HAB_COLOR_SPRING = Color( 0, 255, 127, 255 )
HAB_COLOR_GREEN = Color( 0, 255, 0, 255 )
HAB_COLOR_CHARTREUSE = Color( 127, 255, 0, 255 )
HAB_COLOR_YELLOW = Color( 255, 255, 0, 255 )
HAB_COLOR_ORANGE = Color( 255, 127, 0, 255 )

HAB_COLOR_DEBUG = SERVER and Color( 0, 0, 255, 128 ) or Color( 255, 0, 0, 128 )
HAB_COLOR_ALTDEBUG = SERVER and Color( 0, 255, 0, 128 ) or Color( 255, 255, 0, 128 )

--Cval Types
CVAL_STRING = 0
CVAL_BOOL = 1
CVAL_NUMBER = 2

ANGLE_ZERO = Angle( 0, 0, 0 )

VECTOR_ZERO = Vector( 0, 0, 0 )
VECTOR_ONE = Vector( 1, 1, 1 )
VECTOR_UP = Vector( 0, 0, 1 )
VECTOR_RIGHT = Vector( 0, 1, 0 )
VECTOR_FORWARD = Vector( 1, 0, 0 )


--[[
for i = 0, 127 do
	local sd = util.GetSurfaceData( i )
	print( "SURF_" .. sd.name:upper( ) .. " = " .. i )
end
]]
-- SURF_
SURF_DEFAULT = 0
SURF_SOLIDMETAL = 1
SURF_METAL_BOX = 2
SURF_METAL = 3
SURF_METAL_BOUNCY = 4
SURF_SLIPPERYMETAL = 5
SURF_METALGRATE = 6
SURF_METALVENT = 7
SURF_METALPANEL = 8
SURF_DIRT = 9
SURF_MUD = 10
SURF_SLIPPERYSLIME = 11
SURF_GRASS = 12
SURF_TILE = 13
SURF_WOOD = 14
SURF_WOOD_LOWDENSITY = 15
SURF_WOOD_BOX = 16
SURF_WOOD_CRATE = 17
SURF_WOOD_PLANK = 18
SURF_WOOD_SOLID = 19
SURF_WOOD_FURNITURE = 20
SURF_WOOD_PANEL = 21
SURF_WATER = 22
SURF_SLIME = 23
SURF_QUICKSAND = 24
SURF_WADE = 25
SURF_LADDER = 26
SURF_WOODLADDER = 27
SURF_GLASS = 28
SURF_COMPUTER = 29
SURF_CONCRETE = 30
SURF_ROCK = 31

SURF_PORCELAIN = 32
SURF_BOULDER = 33
SURF_GRAVEL = 34
SURF_BRICK = 35
SURF_CONCRETE_BLOCK = 36
SURF_CHAINLINK = 37
SURF_CHAIN = 38
SURF_FLESH = 39
SURF_BLOODYFLESH = 40
SURF_ALIENFLESH = 41
SURF_ARMORFLESH = 42
SURF_WATERMELON = 43
SURF_SNOW = 44

SURF_ICE = 45
SURF_CARPET = 46
SURF_PLASTER = 47
SURF_CARDBOARD = 48
SURF_PLASTIC_BARREL = 49
SURF_PLASTIC_BOX = 50
SURF_PLASTIC = 51
SURF_ITEM = 52
SURF_FLOATINGSTANDABLE = 53
SURF_SAND = 54
SURF_RUBBER = 55
SURF_RUBBERTIRE = 56
SURF_JEEPTIRE = 57
SURF_SLIDINGRUBBERTIRE = 58
SURF_BRAKINGRUBBERTIRE = 59
SURF_SLIDINGRUBBERTIRE_FRONT = 60
SURF_SLIDINGRUBBERTIRE_REAR = 61
SURF_GLASSBOTTLE = 62
SURF_POTTERY = 63
SURF_GRENADE = 64
SURF_CANISTER = 65
SURF_METAL_BARREL = 66
SURF_FLOATING_METAL_BARREL = 67
SURF_PLASTIC_BARREL_BUOYANT = 68
SURF_ROLLER = 69
SURF_POPCAN = 70
SURF_PAINTCAN = 71
SURF_PAPER = 72
SURF_PAPERCUP = 73
SURF_CEILING_TILE = 74
SURF_WEAPON = 75
SURF_DEFAULT_SILENT = 76
SURF_PLAYER = 77
SURF_PLAYER_CONTROL_CLIP = 78
SURF_NO_DECAL = 79
SURF_FOLIAGE = 80
SURF_METALVEHICLE = 81
SURF_CROWBAR = 82
SURF_ANTLIONSAND = 83
SURF_METAL_SEAFLOORCAR = 84
SURF_GUNSHIP = 85
SURF_STRIDER = 86
SURF_ANTLION = 87
SURF_COMBINE_METAL = 88
SURF_COMBINE_GLASS = 89
SURF_ZOMBIEFLESH = 90
SURF_CAVERN_ROCK = 91
SURF_HUNTER = 92
SURF_JALOPYTIRE = 93
SURF_SLIDINGRUBBERTIRE_JALOPYFRONT = 94
SURF_SLIDINGRUBBERTIRE_JALOPYREAR = 95
SURF_JALOPY = 96
SURF_GMOD_ICE = 97
SURF_GMOD_BOUNCY = 98
SURF_GMOD_SILENT = 99
SURF_STONE = 100
SURF_PHX_TIRE_NORMAL = 101
SURF_GM_PS_EGG = 102
SURF_PHX_EXPLOSIVEBALL = 103
SURF_PHX_FLAKSHELL = 104
SURF_PHX_WW2BOMB = 105
SURF_GM_TORPEDO = 106
SURF_GM_PS_WOODENTIRE = 107
SURF_GM_PS_METALTIRE = 108
SURF_GM_PS_SOCCERBALL = 109
SURF_PHX_RUBBERTIRE = 110
SURF_PHX_RUBBERTIRE2 = 111
SURF_BRASS_BELL_LARGE = 112
SURF_BRASS_BELL_MEDIUM = 113
SURF_BRASS_BELL_SMALL = 114
SURF_BRASS_BELL_SMALLEST = 115
SURF_HAY = 116
SURF_METAL_BARRELLIGHT_HL = 117
SURF_METAL_BARREL_HL = 118
SURF_PLASTIC_BARREL_VERYBUOYANT = 119
SURF_FRICTION_00 = 120
SURF_FRICTION_10 = 121
SURF_FRICTION_25 = 122
SURF_FRICTIONM_00 = 123
SURF_FRICTIONM_10 = 124
SURF_FRICTIONM_25 = 125
