CustomizableWeaponry:addFireSound("CW_KK_INS2_HK416C_FIRE", "weapons/hk416c/mk18_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_HK416C_FIRE_SUPPRESSED", "weapons/hk416c/mk18_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_BOLTBACK", "weapons/hk416c/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_BOLTRELEASE", "weapons/hk416c/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_EMPTY", "weapons/hk416c/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_FIRESELECT", "weapons/hk416c/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_HIT", "weapons/hk416c/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_MAGIN", "weapons/hk416c/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_MAGOUT", "weapons/hk416c/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_HK416C_MAGRELEASE", "weapons/hk416c/handling/mk18_magrelease.wav")
