CustomizableWeaponry:addFireSound("CW_KK_INS2_D4_FIRE", "weapons/d4/mk18_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_D4_FIRE_SUPPRESSED", "weapons/d4/mk18_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_BOLTBACK", "weapons/d4/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_BOLTRELEASE", "weapons/d4/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_EMPTY", "weapons/d4/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_FIRESELECT", "weapons/d4/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_HIT", "weapons/d4/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_MAGIN", "weapons/d4/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_MAGOUT", "weapons/d4/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_D4_MAGRELEASE", "weapons/d4/handling/mk18_magrelease.wav")
