CustomizableWeaponry:addFireSound("CW_KK_INS2_MG36_FIRE", "weapons/mg36/rpk_fp.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_MG36_FIRE_SUPPRESSED", "weapons/mg36/rpk_suppressed_fp.wav", 1, 70, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_BIPODDEPLOY", "weapons/mg36/handling/rpk_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_BIPODRETRACT", "weapons/mg36/handling/rpk_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_BOLTBACK", "weapons/mg36/handling/rpk_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_BOLTRELEASE", "weapons/mg36/handling/rpk_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_DEPLOYGROUNDHIT", "weapons/mg36/handling/rpk_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_EMPTY", "weapons/mg36/handling/rpk_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_ENDDEPLOYEDRELOAD", "weapons/mg36/handling/rpk_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_FETCHMAG", "weapons/mg36/handling/rpk_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_FIRESELECT", "weapons/mg36/handling/rpk_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_MAGIN", "weapons/mg36/handling/rpk_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_MAGOUT", "weapons/mg36/handling/rpk_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_MAGOUTRATTLE", "weapons/mg36/handling/rpk_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_MAGRELEASE", "weapons/mg36/handling/rpk_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MG36_RATTLE", "weapons/mg36/handling/rpk_rattle.wav")
