CustomizableWeaponry:addFireSound("CW_KK_INS2_DEAGLE_FIRE", "weapons/deagle/m45_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_DEAGLE_FIRE_SUPPRESSED", "weapons/deagle/m45_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_BOLTBACK", "weapons/deagle/handling/m45_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_BOLTRELEASE", "weapons/deagle/handling/m45_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_EMPTY", "weapons/deagle/handling/m45_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGHIT", "weapons/deagle/handling/m45_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGIN", "weapons/deagle/handling/m45_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGOUT", "weapons/deagle/handling/m45_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_MAGRELEASE", "weapons/deagle/handling/m45_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DEAGLE_SAFETY", "weapons/deagle/handling/m45_safety.wav")
