CustomizableWeaponry:addFireSound("CW_KK_INS2_BARRETT_FIRE", "weapons/barrett/m14_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_BARRETT_FIRE_SUPPRESSED", "weapons/barrett/m14_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_BOLTBACK", "weapons/barrett/handling/m14_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_BOLTRELEASE", "weapons/barrett/handling/m14_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_EMPTY", "weapons/barrett/m14/m14_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_FIRESELECT", "weapons/barrett/handling/m14_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_MAGIN", "weapons/m14/handling/m14_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_MAGOUT", "weapons/m14/handling/m14_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_MAGOUTRATTLE", "weapons/m14/handling/m14_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_MAGRELEASE", "weapons/m14/handling/m14_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BARRETT_RATTLE", "weapons/m14/handling/m14_rattle.wav")
