CustomizableWeaponry:addFireSound("CW_KK_INS2_BLACKOUT_FIRE", "weapons/blackout/m4a1_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_BLACKOUT_FIRE_SUPPRESSED", "weapons/blackout/m4a1_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_BOLTBACK", "weapons/blackout/handling/m4a1_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_BOLTRELEASE", "weapons/blackout/handling/m4a1_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_EMPTY", "weapons/ak74/handling/ak74_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_FIRESELECT", "weapons/blackout/handling/m4a1_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_HIT", "weapons/blackout/handling/m4a1_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_MAGHITRELEASE", "weapons/blackout/handling/m4a1_maghitrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_MAGIN", "weapons/blackout/handling/m4a1_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_MAGOUT", "weapons/blackout/handling/m4a1_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_BLACKOUT_MAGRELEASE", "weapons/blackout/handling/m4a1_magrelease.wav")
