CustomizableWeaponry:addFireSound("CW_KK_INS2_FATE_FIRE", "weapons/fate/fnfal_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_FATE_FIRE_SUPPRESSED", "weapons/fate/fnfal_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_BOLTBACK", "weapons/fate/handling/fnfal_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_BOLTRELEASE", "weapons/fate/handling/fnfal_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_EMPTY", "weapons/fate/handling/fnfal_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_FIRESELECT", "weapons/fate/handling/fnfal_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_MAGIN", "weapons/fate/handling/fnfal_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_MAGOUT", "weapons/fate/handling/fnfal_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_MAGOUTRATTLE", "weapons/fate/handling/fnfal_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_MAGRELEASE", "weapons/fate/handling/fnfal_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FATE_RATTLE", "weapons/fate/handling/fnfal_rattle.wav")
