CustomizableWeaponry:addFireSound("CW_KK_INS2_PECH_FIRE", "weapons/pecheneg/m249_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_PECH_FIRE_SUPPRESSED", "weapons/pecheneg/m249_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_ARMMOVEMENT1", "weapons/pecheneg/handling/m249_armmovement_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_ARMMOVEMENT2", "weapons/pecheneg/handling/m249_armmovement_01.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BELTALIGN", "weapons/pecheneg/handling/m249_beltalign.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BELTPULLOUT", "weapons/pecheneg/handling/m249_beltpullout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BELTREMOVE", "weapons/pecheneg/handling/m249_beltremove.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BIPODDEPLOY", "weapons/pecheneg/handling/m249_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BIPODRETRACT", "weapons/pecheneg/handling/m249_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BOLTBACK", "weapons/pecheneg/handling/m249_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BOLTRELEASE", "weapons/pecheneg/handling/m249_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_BULLETJINGLE", "weapons/pecheneg/handling/m249_bulletjingle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_COVERCLOSE", "weapons/pecheneg/handling/m249_coverclose.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_COVEROPEN", "weapons/pecheneg/handling/m249_coveropen.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_DEPLOYGROUNDHIT", "weapons/pecheneg/handling/m249_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_EMPTY", "weapons/pecheneg/handling/m249_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_FETCHMAG", "weapons/pecheneg/handling/m249_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_MAGHIT", "weapons/pecheneg/handling/m249_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_MAGIN", "weapons/pecheneg/handling/m249_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_MAGOUT", "weapons/pecheneg/handling/m249_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_MAGOUTFULL", "weapons/pecheneg/handling/m249_magout_full.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_SHOULDER", "weapons/pecheneg/handling/m249_shoulder.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_PECH_THROWAWAYREMAINING", "weapons/pecheneg/handling/m249_throwawayremaining.wav")
