CustomizableWeaponry:addFireSound("CW_KK_INS2_KELTEC_FIRE", "weapons/keltec/fnfal_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_KELTEC_FIRE_SUPPRESSED", "weapons/keltec/fnfal_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_BOLTBACK", "weapons/keltec/handling/fnfal_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_BOLTRELEASE", "weapons/keltec/handling/fnfal_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_EMPTY", "weapons/keltec/handling/fnfal_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_FIRESELECT", "weapons/keltec/handling/fnfal_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_MAGIN", "weapons/keltec/handling/fnfal_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_MAGOUT", "weapons/keltec/handling/fnfal_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_MAGOUTRATTLE", "weapons/keltec/handling/fnfal_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_MAGRELEASE", "weapons/keltec/handling/fnfal_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_KELTEC_RATTLE", "weapons/keltec/handling/fnfal_rattle.wav")
