CustomizableWeaponry:addFireSound("CW_KK_INS2_M60_FIRE", "weapons/m60/m249_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_M60_FIRE_SUPPRESSED", "weapons/m60/m249_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_ARMMOVEMENT1", "weapons/at4/handling/at4_shoulder.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_ARMMOVEMENT2", "weapons/at4/handling/at4_shoulder.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BELTALIGN", "weapons/m60/handling/m249_beltalign.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BELTPULLOUT", "weapons/m60/handling/m249_beltpullout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BELTREMOVE", "weapons/m60/handling/m249_beltremove.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BIPODDEPLOY", "weapons/m60/handling/m249_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BIPODRETRACT", "weapons/m60/handling/m249_bipodretract.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BOLTBACK", "weapons/m60/handling/m249_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BOLTRELEASE", "weapons/m60/handling/m249_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_BULLETJINGLE", "weapons/m60/handling/m249_bulletjingle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_COVERCLOSE", "weapons/m60/handling/m249_coverclose.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_COVEROPEN", "weapons/m60/handling/m249_coveropen.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_DEPLOYGROUNDHIT", "weapons/m60/handling/m249_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_EMPTY", "weapons/m60/handling/m249_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_FETCHMAG", "weapons/m60/handling/m249_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_MAGHIT", "weapons/m60/handling/m249_maghit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_MAGIN", "weapons/m60/handling/m249_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_MAGOUT", "weapons/m60/handling/m249_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_MAGOUTFULL", "weapons/m60/handling/m249_magout_full.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_SHOULDER", "weapons/m60/handling/m249_shoulder.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M60_THROWAWAYREMAINING", "weapons/m60/handling/m249_throwawayremaining.wav")
