CustomizableWeaponry:addFireSound("CW_KK_INS2_NV4_FIRE", "weapons/nv4/m4a1_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_NV4_FIRE_SUPPRESSED", "weapons/nv4/m4a1_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_BOLTBACK", "weapons/nv4/handling/m4a1_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_BOLTRELEASE", "weapons/nv4/handling/m4a1_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_EMPTY", "weapons/nv4/handling/m4a1_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_FIRESELECT", "weapons/nv4/handling/m4a1_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_HIT", "weapons/nv4/handling/m4a1_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_MAGHITRELEASE", "weapons/nv4/handling/m4a1_maghitrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_MAGIN", "weapons/nv4/handling/m4a1_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_MAGOUT", "weapons/nv4/handling/m4a1_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_NV4_MAGRELEASE", "weapons/nv4/handling/m4a1_magrelease.wav")
