CustomizableWeaponry:addFireSound("CW_KK_INS2_IMBEL_FIRE", "weapons/imbel/mk18_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_IMBEL_FIRE_SUPPRESSED", "weapons/imbel/mk18_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_BOLTBACK", "weapons/imbel/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_BOLTRELEASE", "weapons/imbel/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_EMPTY", "weapons/imbel/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_FIRESELECT", "weapons/imbel/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_HIT", "weapons/imbel/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_MAGIN", "weapons/imbel/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_MAGOUT", "weapons/imbel/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_IMBEL_MAGRELEASE", "weapons/imbel/handling/mk18_magrelease.wav")
